using AcademicGateway.Application.Common.Interfaces;
using AcademicGateway.Infrastructure.Identity;
using Domain.Common;
using Domain.Curriculum;
using Domain.Professors;
using Domain.ProjectTemplates;
using Domain.Providers;
using Domain.Skills;
using Domain.Students;
using Domain.SystemStaff;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;

namespace AcademicGateway.Infrastructure.Persistence;

/// <summary>
/// Core database context implementation supporting Identity, multi-aggregate profile extensions, 
/// and transaction-bound dynamic domain event dispatching.
/// </summary>
public class ApplicationDbContext : IdentityDbContext<ApplicationUser, IdentityRole<Guid>, Guid>, IApplicationDbContext
{
    private readonly IServiceProvider _serviceProvider;

    /// <summary>
    /// Initializes a new instance of the <see cref="ApplicationDbContext"/> with required persistence options 
    /// and the native service provider container for handling decoupled domain event routing.
    /// </summary>
    public ApplicationDbContext(
        DbContextOptions<ApplicationDbContext> options,
        IServiceProvider serviceProvider) // Pure native dependency container injection
        : base(options)
    {
        _serviceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));
    }

    // DbSets for Domain Entities
    public DbSet<Student> Students => Set<Student>();
    public DbSet<Provider> Providers => Set<Provider>();
    public DbSet<Professor> Professors => Set<Professor>();
    public DbSet<Skill> Skills => Set<Skill>();
    public DbSet<StudentSkill> StudentSkills => Set<StudentSkill>();
    public DbSet<Major> Majors => Set<Major>();
    public DbSet<Specialty> Specialties => Set<Specialty>();
    public DbSet<StudentMajor> StudentMajors => Set<StudentMajor>();
    public DbSet<StudentSpecialty> StudentSpecialties => Set<StudentSpecialty>();

    // Faculty & Lookup Extensions
    public DbSet<ResearchInterest> ResearchInterests => Set<ResearchInterest>();
    public DbSet<ProfessorResearchInterest> ProfessorResearchInterests => Set<ProfessorResearchInterest>();

    // Core Workflow Mappings
    public DbSet<Reviewer> Reviewers => Set<Reviewer>();
    public DbSet<ProviderApplication> ProviderApplications => Set<ProviderApplication>();
    public DbSet<ProjectTemplate> ProjectTemplates => Set<ProjectTemplate>();
    public DbSet<ProjectTemplateSkill> ProjectTemplateSkills => Set<ProjectTemplateSkill>();
    public DbSet<TechSupportAccount> TechSupportAccounts => Set<TechSupportAccount>();

    /// <summary>
    /// Intercepts entity modifications, processes outbox domain event side effects, 
    /// and commits all changes atomically inside a single database transaction.
    /// </summary>
    public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        // 1. Fully dispatch and evaluate all domain event side effects prior to saving modifications
        await DispatchDomainEventsAsync(cancellationToken);

        // 2. Safely commit state alterations downstream
        return await base.SaveChangesAsync(cancellationToken);
    }

    /// <summary>
    /// Scans the internal EF tracker for entities inheriting from <see cref="BaseEntity"/>, extracts 
    /// queued domain events, clears queues to prevent execution loops, and dynamically routes them 
    /// to concrete registrations of <see cref="IDomainEventHandler{TEvent}"/>.
    /// </summary>
    private async Task DispatchDomainEventsAsync(CancellationToken cancellationToken)
    {
        // Utilizes a continuous processing evaluation loop to cleanly trap any cascading events 
        // generated by subsequent handlers during the exact same execution scope.
        while (true)
        {
            var domainEntities = ChangeTracker
                .Entries<BaseEntity>()
                .Where(x => x.Entity.DomainEvents != null && x.Entity.DomainEvents.Any())
                .ToList();

            if (!domainEntities.Any())
            {
                break;
            }

            var domainEvents = domainEntities
                .SelectMany(x => x.Entity.DomainEvents)
                .ToList();

            // Clear events immediately before starting async executions to rule out infinity loops
            foreach (var domainEntity in domainEntities)
            {
                domainEntity.Entity.ClearDomainEvents();
            }

            foreach (var domainEvent in domainEvents)
            {
                // Build the distinct dynamic tracking handler lookup signature: IDomainEventHandler<YourSpecificEvent>
                var handlerInterfaceType = typeof(IDomainEventHandler<>).MakeGenericType(domainEvent.GetType());

                // Fetch registered concrete applications out of the Microsoft container natively
                var handlers = _serviceProvider.GetServices(handlerInterfaceType);

                foreach (var handler in handlers)
                {
                    if (handler == null) continue;

                    // Safely locate the HandleAsync method on the generic interface target
                    var method = handlerInterfaceType.GetMethod(nameof(IDomainEventHandler<IDomainEvent>.HandleAsync));

                    if (method != null)
                    {
                        // Invoke the handler dynamically and forward arguments down
                        await (Task)method.Invoke(handler, new object[] { domainEvent, cancellationToken })!;
                    }
                }
            }
        }
    }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        // Crucial: Identity needs its own internal mappings configured first
        base.OnModelCreating(builder);

        // ==========================================
        // 1-to-1 Profile Extension Configurations
        // ==========================================

        builder.Entity<Student>(entity =>
        {
            entity.HasKey(s => s.Id);
            entity.HasOne<ApplicationUser>()
                  .WithOne()
                  .HasForeignKey<Student>(s => s.Id)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        builder.Entity<Provider>(entity =>
        {
            entity.HasKey(p => p.Id);
            entity.HasOne<ApplicationUser>()
                  .WithOne()
                  .HasForeignKey<Provider>(p => p.Id)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        builder.Entity<Professor>(entity =>
        {
            entity.HasKey(p => p.Id);
            entity.HasOne<ApplicationUser>()
                  .WithOne()
                  .HasForeignKey<Professor>(p => p.Id)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        builder.Entity<Reviewer>(entity =>
        {
            entity.HasKey(r => r.Id);
            entity.HasOne<ApplicationUser>()
                  .WithOne()
                  .HasForeignKey<Reviewer>(r => r.Id)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        builder.Entity<TechSupportAccount>(entity =>
        {
            entity.HasKey(ts => ts.Id);
            entity.HasOne<ApplicationUser>()
                  .WithOne()
                  .HasForeignKey<TechSupportAccount>(ts => ts.Id)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        // ==========================================
        // Many-to-Many Configuration: Student Relations
        // ==========================================

        builder.Entity<StudentSkill>(entity =>
        {
            entity.HasKey(ss => new { ss.StudentId, ss.SkillId });

            entity.HasOne(ss => ss.Student)
                  .WithMany(s => s.StudentSkills)
                  .HasForeignKey(ss => ss.StudentId)
                  .OnDelete(DeleteBehavior.Cascade);

            entity.HasOne(ss => ss.Skill)
                  .WithMany(s => s.StudentSkills)
                  .HasForeignKey(ss => ss.SkillId)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        builder.Entity<StudentMajor>(entity =>
        {
            entity.HasKey(sm => new { sm.StudentId, sm.MajorId });

            entity.HasOne(sm => sm.Student)
                  .WithMany(s => s.StudentMajors)
                  .HasForeignKey(sm => sm.StudentId)
                  .OnDelete(DeleteBehavior.Cascade);

            entity.HasOne(sm => sm.Major)
                  .WithMany(m => m.StudentMajors)
                  .HasForeignKey(sm => sm.MajorId)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        builder.Entity<StudentSpecialty>(entity =>
        {
            entity.HasKey(ss => new { ss.StudentId, ss.SpecialtyId });

            entity.HasOne(ss => ss.Student)
                  .WithMany(s => s.StudentSpecialties)
                  .HasForeignKey(ss => ss.StudentId)
                  .OnDelete(DeleteBehavior.Cascade);

            entity.HasOne(ss => ss.Specialty)
                  .WithMany(s => s.StudentSpecialties)
                  .HasForeignKey(ss => ss.SpecialtyId)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        // ==========================================
        // Many-to-Many Configuration: Professor Relations
        // ==========================================

        builder.Entity<ProfessorResearchInterest>(entity =>
        {
            entity.HasKey(pri => new { pri.ProfessorId, pri.ResearchInterestId });

            entity.HasOne(pri => pri.Professor)
                  .WithMany(p => p.ProfessorResearchInterests)
                  .HasForeignKey(pri => pri.ProfessorId)
                  .OnDelete(DeleteBehavior.Cascade);

            entity.HasOne(pri => pri.ResearchInterest)
                  .WithMany(r => r.ProfessorResearchInterests)
                  .HasForeignKey(pri => pri.ResearchInterestId)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        // ==========================================
        // 1-to-Many Configuration: Curriculum
        // ==========================================

        builder.Entity<Specialty>(entity =>
        {
            entity.HasOne(s => s.Major)
                  .WithMany(m => m.Specialties)
                  .HasForeignKey(s => s.MajorId)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        // ==========================================
        // Core Workflow Funnel Configurations
        // ==========================================

        builder.Entity<ProviderApplication>(entity =>
        {
            entity.HasKey(pa => pa.Id);

            entity.HasOne(pa => pa.Provider)
                  .WithMany()
                  .HasForeignKey(pa => pa.ProviderId)
                  .OnDelete(DeleteBehavior.Cascade);

            entity.HasOne(pa => pa.ReviewedBy)
                  .WithMany(r => r.ReviewedApplications)
                  .HasForeignKey(pa => pa.ReviewedById)
                  .OnDelete(DeleteBehavior.SetNull);
        });

        builder.Entity<ProjectTemplate>(entity =>
        {
            entity.HasKey(pt => pt.Id);

            entity.HasOne(pt => pt.Provider)
                  .WithMany(p => p.ProjectTemplates)
                  .HasForeignKey(pt => pt.ProviderId)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        builder.Entity<ProjectTemplateSkill>(entity =>
        {
            entity.HasKey(pts => new { pts.ProjectTemplateId, pts.SkillId });

            entity.HasOne(pts => pts.ProjectTemplate)
                  .WithMany(t => t.ProjectTemplateSkills)
                  .HasForeignKey(pts => pts.ProjectTemplateId)
                  .OnDelete(DeleteBehavior.Cascade);

            entity.HasOne(pts => pts.Skill)
                  .WithMany()
                  .HasForeignKey(pts => pts.SkillId)
                  .OnDelete(DeleteBehavior.Cascade);
        });
    }
}