// <auto-generated />
using System;
using AcademicGateway.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260628035323_AddProviderFunnelAndTemplates")]
    partial class AddProviderFunnelAndTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AcademicGateway.Domain.Entities.Major", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_majors");

                    b.ToTable("majors", (string)null);
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.Professor", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("AcademicDepartment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("academic_department");

                    b.HasKey("UserId")
                        .HasName("pk_professors");

                    b.ToTable("professors", (string)null);
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.ProjectTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ExpectedDurationWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("expected_duration_weeks");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_id");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_project_templates");

                    b.HasIndex("ApprovedById")
                        .HasDatabaseName("ix_project_templates_approved_by_id");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_project_templates_provider_id");

                    b.ToTable("project_templates", (string)null);
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.ProjectTemplateSkill", b =>
                {
                    b.Property<Guid>("ProjectTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_template_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.HasKey("ProjectTemplateId", "SkillId")
                        .HasName("pk_project_template_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_project_template_skills_skill_id");

                    b.ToTable("project_template_skills", (string)null);
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.Provider", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("industry");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_name");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text")
                        .HasColumnName("website_url");

                    b.HasKey("UserId")
                        .HasName("pk_providers");

                    b.ToTable("providers", (string)null);
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.ProviderApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyDetails")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_details");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_id");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("VerificationDocumentsUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification_documents_url");

                    b.HasKey("Id")
                        .HasName("pk_provider_applications");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_provider_applications_provider_id");

                    b.HasIndex("ReviewedById")
                        .HasDatabaseName("ix_provider_applications_reviewed_by_id");

                    b.ToTable("provider_applications", (string)null);
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.Reviewer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_user_id");

                    b.HasKey("Id")
                        .HasName("pk_reviewers");

                    b.HasIndex("IdentityUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviewers_identity_user_id");

                    b.ToTable("reviewers", (string)null);
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.Specialty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("uuid")
                        .HasColumnName("major_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_specialties");

                    b.HasIndex("MajorId")
                        .HasDatabaseName("ix_specialties_major_id");

                    b.ToTable("specialties", (string)null);
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.Student", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("integer")
                        .HasColumnName("graduation_year");

                    b.HasKey("UserId")
                        .HasName("pk_students");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.StudentMajor", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("uuid")
                        .HasColumnName("major_id");

                    b.HasKey("StudentId", "MajorId")
                        .HasName("pk_student_majors");

                    b.HasIndex("MajorId")
                        .HasDatabaseName("ix_student_majors_major_id");

                    b.ToTable("student_majors", (string)null);
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.StudentSkill", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.HasKey("StudentId", "SkillId")
                        .HasName("pk_student_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_student_skills_skill_id");

                    b.ToTable("student_skills", (string)null);
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.StudentSpecialty", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uuid")
                        .HasColumnName("specialty_id");

                    b.HasKey("StudentId", "SpecialtyId")
                        .HasName("pk_student_specialties");

                    b.HasIndex("SpecialtyId")
                        .HasDatabaseName("ix_student_specialties_specialty_id");

                    b.ToTable("student_specialties", (string)null);
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.TechSupportAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_id");

                    b.HasKey("Id")
                        .HasName("pk_tech_support_accounts");

                    b.HasIndex("IdentityUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_tech_support_accounts_identity_user_id");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_tech_support_accounts_provider_id");

                    b.ToTable("tech_support_accounts", (string)null);
                });

            modelBuilder.Entity("AcademicGateway.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.Professor", b =>
                {
                    b.HasOne("AcademicGateway.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("AcademicGateway.Domain.Entities.Professor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_professors_asp_net_users_user_id");
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.ProjectTemplate", b =>
                {
                    b.HasOne("AcademicGateway.Domain.Entities.Reviewer", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_project_templates_reviewers_approved_by_id");

                    b.HasOne("AcademicGateway.Domain.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_templates_providers_provider_id");

                    b.Navigation("ApprovedBy");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.ProjectTemplateSkill", b =>
                {
                    b.HasOne("AcademicGateway.Domain.Entities.ProjectTemplate", "ProjectTemplate")
                        .WithMany("TemplateSkills")
                        .HasForeignKey("ProjectTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_template_skills_project_templates_project_template_");

                    b.HasOne("AcademicGateway.Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_template_skills_skills_skill_id");

                    b.Navigation("ProjectTemplate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.Provider", b =>
                {
                    b.HasOne("AcademicGateway.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("AcademicGateway.Domain.Entities.Provider", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_providers_asp_net_users_user_id");
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.ProviderApplication", b =>
                {
                    b.HasOne("AcademicGateway.Domain.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_applications_providers_provider_id");

                    b.HasOne("AcademicGateway.Domain.Entities.Reviewer", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_provider_applications_reviewers_reviewed_by_id");

                    b.Navigation("Provider");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.Reviewer", b =>
                {
                    b.HasOne("AcademicGateway.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("AcademicGateway.Domain.Entities.Reviewer", "IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviewers_asp_net_users_identity_user_id");
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.Specialty", b =>
                {
                    b.HasOne("AcademicGateway.Domain.Entities.Major", "Major")
                        .WithMany("Specialties")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_specialties_majors_major_id");

                    b.Navigation("Major");
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.Student", b =>
                {
                    b.HasOne("AcademicGateway.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("AcademicGateway.Domain.Entities.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_asp_net_users_user_id");
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.StudentMajor", b =>
                {
                    b.HasOne("AcademicGateway.Domain.Entities.Major", "Major")
                        .WithMany("StudentMajors")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_majors_majors_major_id");

                    b.HasOne("AcademicGateway.Domain.Entities.Student", "Student")
                        .WithMany("StudentMajors")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_majors_students_student_id");

                    b.Navigation("Major");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.StudentSkill", b =>
                {
                    b.HasOne("AcademicGateway.Domain.Entities.Skill", "Skill")
                        .WithMany("StudentSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_skills_skills_skill_id");

                    b.HasOne("AcademicGateway.Domain.Entities.Student", "Student")
                        .WithMany("StudentSkills")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_skills_students_student_id");

                    b.Navigation("Skill");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.StudentSpecialty", b =>
                {
                    b.HasOne("AcademicGateway.Domain.Entities.Specialty", "Specialty")
                        .WithMany("StudentSpecialties")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_specialties_specialties_specialty_id");

                    b.HasOne("AcademicGateway.Domain.Entities.Student", "Student")
                        .WithMany("StudentSpecialties")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_specialties_students_student_id");

                    b.Navigation("Specialty");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.TechSupportAccount", b =>
                {
                    b.HasOne("AcademicGateway.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("AcademicGateway.Domain.Entities.TechSupportAccount", "IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tech_support_accounts_asp_net_users_identity_user_id");

                    b.HasOne("AcademicGateway.Domain.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tech_support_accounts_providers_provider_id");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AcademicGateway.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AcademicGateway.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("AcademicGateway.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AcademicGateway.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.Major", b =>
                {
                    b.Navigation("Specialties");

                    b.Navigation("StudentMajors");
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.ProjectTemplate", b =>
                {
                    b.Navigation("TemplateSkills");
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.Skill", b =>
                {
                    b.Navigation("StudentSkills");
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.Specialty", b =>
                {
                    b.Navigation("StudentSpecialties");
                });

            modelBuilder.Entity("AcademicGateway.Domain.Entities.Student", b =>
                {
                    b.Navigation("StudentMajors");

                    b.Navigation("StudentSkills");

                    b.Navigation("StudentSpecialties");
                });
#pragma warning restore 612, 618
        }
    }
}
