// <auto-generated />
using System;
using Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260701164607_InitialCoreDbSchema")]
    partial class InitialCoreDbSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AcademicGateway.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Curriculum.Major", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_majors");

                    b.ToTable("Majors", (string)null);
                });

            modelBuilder.Entity("Domain.Curriculum.Specialty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("uuid")
                        .HasColumnName("major_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_specialties");

                    b.HasIndex("MajorId")
                        .HasDatabaseName("ix_specialties_major_id");

                    b.ToTable("Specialties", (string)null);
                });

            modelBuilder.Entity("Domain.Professors.Professor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CurrentProjectCount")
                        .HasColumnType("integer")
                        .HasColumnName("current_project_count");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("department");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<int>("MaxSupervisionCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("max_supervision_capacity");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rank");

                    b.HasKey("Id")
                        .HasName("pk_professors");

                    b.ToTable("Professors", (string)null);
                });

            modelBuilder.Entity("Domain.Professors.ProfessorResearchInterest", b =>
                {
                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("professor_id");

                    b.Property<Guid>("ResearchInterestId")
                        .HasColumnType("uuid")
                        .HasColumnName("research_interest_id");

                    b.HasKey("ProfessorId", "ResearchInterestId")
                        .HasName("pk_professor_research_interests");

                    b.HasIndex("ResearchInterestId")
                        .HasDatabaseName("ix_professor_research_interests_research_interest_id");

                    b.ToTable("ProfessorResearchInterests", (string)null);
                });

            modelBuilder.Entity("Domain.Professors.ResearchInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("area");

                    b.HasKey("Id")
                        .HasName("pk_research_interests");

                    b.ToTable("ResearchInterests", (string)null);
                });

            modelBuilder.Entity("Domain.ProjectTemplates.ProjectTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<string>("ReviewerFeedback")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reviewer_feedback");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_project_templates");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_project_templates_provider_id");

                    b.ToTable("ProjectTemplates", (string)null);
                });

            modelBuilder.Entity("Domain.ProjectTemplates.ProjectTemplateSkill", b =>
                {
                    b.Property<Guid>("ProjectTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_template_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.HasKey("ProjectTemplateId", "SkillId")
                        .HasName("pk_project_template_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_project_template_skills_skill_id");

                    b.ToTable("ProjectTemplateSkills", (string)null);
                });

            modelBuilder.Entity("Domain.Providers.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("company_description");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_providers");

                    b.ToTable("Providers", (string)null);
                });

            modelBuilder.Entity("Domain.Providers.ProviderApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyDetails")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("company_details");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("VerificationDocumentsUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("verification_documents_url");

                    b.HasKey("Id")
                        .HasName("pk_provider_applications");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_provider_applications_provider_id");

                    b.HasIndex("ReviewedById")
                        .HasDatabaseName("ix_provider_applications_reviewed_by_id");

                    b.ToTable("ProviderApplications", (string)null);
                });

            modelBuilder.Entity("Domain.Providers.TechSupportAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("StaffNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("staff_number");

                    b.Property<string>("SupportTier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("support_tier");

                    b.HasKey("Id")
                        .HasName("pk_tech_support_accounts");

                    b.ToTable("TechSupportAccounts", (string)null);
                });

            modelBuilder.Entity("Domain.Skills.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_skills_name");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("Domain.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("integer")
                        .HasColumnName("graduation_year");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("Domain.Students.StudentMajor", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("uuid")
                        .HasColumnName("major_id");

                    b.HasKey("StudentId", "MajorId")
                        .HasName("pk_student_majors");

                    b.HasIndex("MajorId")
                        .HasDatabaseName("ix_student_majors_major_id");

                    b.ToTable("StudentMajors", (string)null);
                });

            modelBuilder.Entity("Domain.Students.StudentSkill", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.HasKey("StudentId", "SkillId")
                        .HasName("pk_student_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_student_skills_skill_id");

                    b.ToTable("StudentSkills", (string)null);
                });

            modelBuilder.Entity("Domain.Students.StudentSpecialty", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uuid")
                        .HasColumnName("specialty_id");

                    b.HasKey("StudentId", "SpecialtyId")
                        .HasName("pk_student_specialties");

                    b.HasIndex("SpecialtyId")
                        .HasDatabaseName("ix_student_specialties_specialty_id");

                    b.ToTable("StudentSpecialties", (string)null);
                });

            modelBuilder.Entity("Domain.SystemStaff.Reviewer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.HasKey("Id")
                        .HasName("pk_reviewers");

                    b.ToTable("Reviewers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Curriculum.Specialty", b =>
                {
                    b.HasOne("Domain.Curriculum.Major", "Major")
                        .WithMany("Specialties")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_specialties_majors_major_id");

                    b.Navigation("Major");
                });

            modelBuilder.Entity("Domain.Professors.Professor", b =>
                {
                    b.HasOne("AcademicGateway.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Domain.Professors.Professor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_professors_asp_net_users_id");
                });

            modelBuilder.Entity("Domain.Professors.ProfessorResearchInterest", b =>
                {
                    b.HasOne("Domain.Professors.Professor", "Professor")
                        .WithMany("ResearchInterests")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_professor_research_interests_professors_professor_id");

                    b.HasOne("Domain.Professors.ResearchInterest", "ResearchInterest")
                        .WithMany("ProfessorLinks")
                        .HasForeignKey("ResearchInterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_professor_research_interests_research_interests_research_inte");

                    b.Navigation("Professor");

                    b.Navigation("ResearchInterest");
                });

            modelBuilder.Entity("Domain.ProjectTemplates.ProjectTemplate", b =>
                {
                    b.HasOne("Domain.Providers.Provider", "Provider")
                        .WithMany("ProjectTemplates")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_templates_providers_provider_id");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Domain.ProjectTemplates.ProjectTemplateSkill", b =>
                {
                    b.HasOne("Domain.ProjectTemplates.ProjectTemplate", "ProjectTemplate")
                        .WithMany("ProjectTemplateSkills")
                        .HasForeignKey("ProjectTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_template_skills_project_templates_project_template_id");

                    b.HasOne("Domain.Skills.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_template_skills_skills_skill_id");

                    b.Navigation("ProjectTemplate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Domain.Providers.Provider", b =>
                {
                    b.HasOne("AcademicGateway.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Domain.Providers.Provider", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_providers_asp_net_users_id");
                });

            modelBuilder.Entity("Domain.Providers.ProviderApplication", b =>
                {
                    b.HasOne("Domain.Providers.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_applications_providers_provider_id");

                    b.HasOne("Domain.SystemStaff.Reviewer", "ReviewedBy")
                        .WithMany("ReviewedApplications")
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_provider_applications_reviewers_reviewed_by_id");

                    b.Navigation("Provider");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("Domain.Providers.TechSupportAccount", b =>
                {
                    b.HasOne("AcademicGateway.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Domain.Providers.TechSupportAccount", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tech_support_accounts_asp_net_users_id");
                });

            modelBuilder.Entity("Domain.Students.Student", b =>
                {
                    b.HasOne("AcademicGateway.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Domain.Students.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_asp_net_users_id");
                });

            modelBuilder.Entity("Domain.Students.StudentMajor", b =>
                {
                    b.HasOne("Domain.Curriculum.Major", "Major")
                        .WithMany("StudentMajors")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_majors_majors_major_id");

                    b.HasOne("Domain.Students.Student", "Student")
                        .WithMany("StudentMajors")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_majors_students_student_id");

                    b.Navigation("Major");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Domain.Students.StudentSkill", b =>
                {
                    b.HasOne("Domain.Skills.Skill", "Skill")
                        .WithMany("StudentSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_skills_skills_skill_id");

                    b.HasOne("Domain.Students.Student", "Student")
                        .WithMany("StudentSkills")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_skills_students_student_id");

                    b.Navigation("Skill");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Domain.Students.StudentSpecialty", b =>
                {
                    b.HasOne("Domain.Curriculum.Specialty", "Specialty")
                        .WithMany("StudentSpecialties")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_specialties_specialties_specialty_id");

                    b.HasOne("Domain.Students.Student", "Student")
                        .WithMany("StudentSpecialties")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_specialties_students_student_id");

                    b.Navigation("Specialty");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Domain.SystemStaff.Reviewer", b =>
                {
                    b.HasOne("AcademicGateway.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Domain.SystemStaff.Reviewer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviewers_asp_net_users_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AcademicGateway.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AcademicGateway.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("AcademicGateway.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AcademicGateway.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Domain.Curriculum.Major", b =>
                {
                    b.Navigation("Specialties");

                    b.Navigation("StudentMajors");
                });

            modelBuilder.Entity("Domain.Curriculum.Specialty", b =>
                {
                    b.Navigation("StudentSpecialties");
                });

            modelBuilder.Entity("Domain.Professors.Professor", b =>
                {
                    b.Navigation("ResearchInterests");
                });

            modelBuilder.Entity("Domain.Professors.ResearchInterest", b =>
                {
                    b.Navigation("ProfessorLinks");
                });

            modelBuilder.Entity("Domain.ProjectTemplates.ProjectTemplate", b =>
                {
                    b.Navigation("ProjectTemplateSkills");
                });

            modelBuilder.Entity("Domain.Providers.Provider", b =>
                {
                    b.Navigation("ProjectTemplates");
                });

            modelBuilder.Entity("Domain.Skills.Skill", b =>
                {
                    b.Navigation("StudentSkills");
                });

            modelBuilder.Entity("Domain.Students.Student", b =>
                {
                    b.Navigation("StudentMajors");

                    b.Navigation("StudentSkills");

                    b.Navigation("StudentSpecialties");
                });

            modelBuilder.Entity("Domain.SystemStaff.Reviewer", b =>
                {
                    b.Navigation("ReviewedApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
