using System;
using System.Collections.Generic;
using System.Linq;
using AcademicGateway.Domain.Common;
using AcademicGateway.Domain.Common.Enums;
using AcademicGateway.Domain.ProjectTemplates.Exceptions;
using AcademicGateway.Domain.ProjectTemplates.Events;
using AcademicGateway.Domain.Providers;
using AcademicGateway.Domain.ProjectInstances.Enums;
using AcademicGateway.Domain.ProjectInstances;
using AcademicGateway.Domain.ProjectTemplates.Enums;
using AcademicGateway.Domain.ProjectInstances.Services;

namespace AcademicGateway.Domain.ProjectTemplates;

/// <summary>
/// Represents a reusable project blueprint proposed by a verified provider, which undergoes 
/// a collaborative review pipeline before becoming available to students. Serves as the 
/// Aggregate Root for the blueprint domain graph.
/// </summary>
public class ProjectTemplate : BaseEntity
{
    private readonly List<ProjectTemplateSkill> _projectTemplateSkills = new();
    private readonly List<GlobalMilestone> _globalMilestones = new();

    /// <summary>
    /// Gets the unique identifier for the project template.
    /// </summary>
    public Guid Id { get; private set; }

    /// <summary>
    /// Gets the headline title of the project template.
    /// </summary>
    public string Title { get; private set; } = string.Empty;

    /// <summary>
    /// Gets the detailed description mapping requirements, scope, and objectives of the project.
    /// </summary>
    public string Description { get; private set; } = string.Empty;

    /// <summary>
    /// Gets the current lifecycle state of the template within the curation pipeline.
    /// </summary>
    public ProjectTemplateStatus Status { get; private set; }

    /// <summary>
    /// Gets the unique identifier of the creating provider account.
    /// </summary>
    public Guid ProviderId { get; private set; }

    /// <summary>
    /// Gets the operational feedback, change requests, or rejection reasons logged by the evaluating reviewer.
    /// </summary>
    public string? ReviewerFeedback { get; private set; }

    /// <summary>
    /// Gets the chronological timestamp specifying exactly when this template blueprint was initialized in the system.
    /// Used natively to power operational reviewer dashboards and FIFO clearance queues.
    /// </summary>
    public DateTime CreatedAt { get; private set; }

    /// <summary>
    /// Gets the navigation property for the creating partner profile.
    /// </summary>
    public Provider Provider { get; private set; } = null!;

    /// <summary>
    /// Gets the read-only tracking collection of specific skill competencies mapped to this template.
    /// </summary>
    public IReadOnlyCollection<ProjectTemplateSkill> ProjectTemplateSkills => _projectTemplateSkills.AsReadOnly();

    /// <summary>
    /// Gets the read-only collection of milestones associated with this blueprint.
    /// </summary>
    public IReadOnlyCollection<GlobalMilestone> GlobalMilestones => _globalMilestones.AsReadOnly();

    /// <summary>
    /// EF Core constructor requirement. Prevents bypass of standard domain constraints during persistence hydration.
    /// </summary>
    private ProjectTemplate()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="ProjectTemplate"/> tracking model in Draft mode.
    /// </summary>
    /// <param name="title">The structural title of the project blueprint.</param>
    /// <param name="description">The core overview requirements text.</param>
    /// <param name="providerId">The identity tracker code mapping back to the owner profile.</param>
    /// <param name="createdAt">The deterministic timeline audit timestamp generated by an isolated clock infrastructure wrapper.</param>
    /// <exception cref="InvalidTemplateDetailsException">Thrown when fundamental text parameters fail validation checks.</exception>
    public ProjectTemplate(string title, string description, Guid providerId, DateTime createdAt)
    {
        if (providerId == Guid.Empty)
        {
            throw new InvalidTemplateDetailsException("Provider ID cannot be an empty Guid.");
        }

        Id = Guid.NewGuid();
        ProviderId = providerId;
        Status = ProjectTemplateStatus.Draft;
        CreatedAt = createdAt;

        UpdateDetails(title, description);

        // Append creation domain event message natively onto the tracking queue
        AddDomainEvent(new ProjectTemplateCreatedEvent(Id, ProviderId, Title));
    }

    // ==========================================
    // MILESTONE MANAGEMENT (MUTATORS)
    // ==========================================

    /// <summary>
    /// Adds a new global milestone blueprint configuration to this template aggregate root.
    /// </summary>
    /// <param name="title">The title of the milestone.</param>
    /// <param name="description">The detailed milestone implementation instructions.</param>
    /// <param name="expectedEffortInHours">The effort-based scheduling estimation value.</param>
    /// <param name="wbsWeight">The operational work progress distribution weight percentage.</param>
    /// <param name="gradingWeight">The academic credit valuation weight percentage.</param>
    /// <exception cref="InvalidTemplateStatusException">Thrown if the template is already locked from edits.</exception>
    public void AddMilestone(string title, string description, decimal expectedEffortInHours, decimal wbsWeight, decimal gradingWeight)
    {
        if (Status == ProjectTemplateStatus.Approved || Status == ProjectTemplateStatus.Rejected)
        {
            throw new InvalidTemplateStatusException(Status, nameof(AddMilestone));
        }

        if (expectedEffortInHours <= 0)
        {
            throw new InvalidTemplateDetailsException("Expected effort must be greater than zero hours.");
        }

        var milestone = new GlobalMilestone(this.Id, title, description, expectedEffortInHours, wbsWeight, gradingWeight);
        _globalMilestones.Add(milestone);
    }

    /// <summary>
    /// Updates the architectural parameters and requirements criteria of an existing global milestone configuration.
    /// </summary>
    /// <param name="milestoneId">The tracking identifier code of the milestone blueprint node to modify.</param>
    /// <param name="title">The updated descriptive headline title assigned to the milestone phase.</param>
    /// <param name="description">The revised contextual parameters mapping work item scope.</param>
    /// <param name="expectedEffortInHours">The updated effort constraint metrics measured in project work hours.</param>
    /// <param name="wbsWeight">The updated operational progress weight distribution percentage.</param>
    /// <param name="gradingWeight">The updated academic grading metric assignment percentage.</param>
    /// <exception cref="InvalidTemplateStatusException">Thrown if the aggregate root has been locked from lifecycle edits.</exception>
    /// <exception cref="InvalidTemplateDetailsException">Thrown if the milestone tracking row is missing or updates violate text validation constraints.</exception>
    public void UpdateMilestone(Guid milestoneId, string title, string description, decimal expectedEffortInHours, decimal wbsWeight, decimal gradingWeight)
    {
        if (Status == ProjectTemplateStatus.Approved || Status == ProjectTemplateStatus.Rejected)
        {
            throw new InvalidTemplateStatusException(Status, nameof(UpdateMilestone));
        }

        var milestone = _globalMilestones.FirstOrDefault(m => m.Id == milestoneId);
        if (milestone == null)
        {
            throw new InvalidTemplateDetailsException("The requested milestone blueprint node does not exist within this template configuration context.");
        }

        milestone.UpdateDetails(title, description, expectedEffortInHours, wbsWeight, gradingWeight);
    }

    /// <summary>
    /// Safely purges a global milestone blueprint node from the aggregate tracking layout, cascading deletion constraints across all dependent graph links.
    /// </summary>
    /// <param name="milestoneId">The unique key tracking identifier of the milestone blueprint node to drop.</param>
    /// <exception cref="InvalidTemplateStatusException">Thrown if the aggregate root state is currently immutable.</exception>
    /// <exception cref="InvalidTemplateDetailsException">Thrown if the target milestone node could not be resolved.</exception>
    public void RemoveMilestone(Guid milestoneId)
    {
        if (Status == ProjectTemplateStatus.Approved || Status == ProjectTemplateStatus.Rejected)
        {
            throw new InvalidTemplateStatusException(Status, nameof(RemoveMilestone));
        }

        var milestoneToRemove = _globalMilestones.FirstOrDefault(m => m.Id == milestoneId);
        if (milestoneToRemove == null)
        {
            throw new InvalidTemplateDetailsException("The targeted milestone blueprint node does not exist within this template configuration context.");
        }

        foreach (var milestone in _globalMilestones)
        {
            milestone.RemovePredecessor(milestoneId);
        }

        _globalMilestones.Remove(milestoneToRemove);
    }

    // ==========================================
    // NESTED TASK ROUTING (PASS-THROUGH METHODS)
    // ==========================================

    /// <summary>
    /// Routes the creation of a nested global task blueprint configuration down to a specific milestone.
    /// </summary>
    public void AddGlobalTaskToMilestone(Guid milestoneId, string title, string description, decimal weight, DeliverableType requiredDeliverableType)
    {
        if (Status == ProjectTemplateStatus.Approved || Status == ProjectTemplateStatus.Rejected)
        {
            throw new InvalidTemplateStatusException(Status, nameof(AddGlobalTaskToMilestone));
        }

        var milestone = _globalMilestones.FirstOrDefault(m => m.Id == milestoneId);
        if (milestone == null)
        {
            throw new InvalidTemplateDetailsException("The target milestone blueprint node does not exist within this template configuration context.");
        }

        milestone.AddTask(title, description, weight, requiredDeliverableType);
    }

    /// <summary>
    /// Routes the update of a nested global task blueprint configuration down to a specific milestone container.
    /// </summary>
    public void UpdateGlobalTaskInMilestone(Guid milestoneId, Guid taskId, string title, string description, decimal weight, DeliverableType requiredDeliverableType)
    {
        if (Status == ProjectTemplateStatus.Approved || Status == ProjectTemplateStatus.Rejected)
        {
            throw new InvalidTemplateStatusException(Status, nameof(UpdateGlobalTaskInMilestone));
        }

        var milestone = _globalMilestones.FirstOrDefault(m => m.Id == milestoneId);
        if (milestone == null)
        {
            throw new InvalidTemplateDetailsException("The target milestone blueprint node does not exist within this template configuration context.");
        }

        milestone.UpdateTask(taskId, title, description, weight, requiredDeliverableType);
    }

    /// <summary>
    /// Routes the removal of a nested global task blueprint configuration down to a specific milestone container.
    /// </summary>
    public void RemoveGlobalTaskFromMilestone(Guid milestoneId, Guid taskId)
    {
        if (Status == ProjectTemplateStatus.Approved || Status == ProjectTemplateStatus.Rejected)
        {
            throw new InvalidTemplateStatusException(Status, nameof(RemoveGlobalTaskFromMilestone));
        }

        var milestone = _globalMilestones.FirstOrDefault(m => m.Id == milestoneId);
        if (milestone == null)
        {
            throw new InvalidTemplateDetailsException("The target milestone blueprint node does not exist within this template configuration context.");
        }

        milestone.RemoveTask(taskId);
    }

    // ==========================================
    // GRAPH DEPENDENCY METHODS (DAG VALIDATION)
    // ==========================================

    /// <summary>
    /// Establishes a graph dependency constraint between two internal blueprint milestones with cyclic validation protection.
    /// </summary>
    public void AddMilestoneDependency(Guid successorId, Guid predecessorId, DependencyType type)
    {
        if (Status == ProjectTemplateStatus.Approved || Status == ProjectTemplateStatus.Rejected)
        {
            throw new InvalidTemplateStatusException(Status, nameof(AddMilestoneDependency));
        }

        var successor = _globalMilestones.FirstOrDefault(m => m.Id == successorId);
        var predecessor = _globalMilestones.FirstOrDefault(m => m.Id == predecessorId);

        if (successor == null || predecessor == null)
        {
            throw new InvalidTemplateDetailsException("Both target milestones must exist within this template context.");
        }

        successor.AddPredecessor(predecessorId, type);
        EnsureGraphIsAcyclic();
    }

    /// <summary>
    /// Severs an existing timeline dependency restriction constraint link separating two internal blueprint milestones.
    /// </summary>
    public void RemoveMilestoneDependency(Guid successorId, Guid predecessorId)
    {
        if (Status == ProjectTemplateStatus.Approved || Status == ProjectTemplateStatus.Rejected)
        {
            throw new InvalidTemplateStatusException(Status, nameof(RemoveMilestoneDependency));
        }

        var successor = _globalMilestones.FirstOrDefault(m => m.Id == successorId);
        if (successor == null)
        {
            throw new InvalidTemplateDetailsException("The requested successor milestone configuration node does not exist within this template context.");
        }

        var predecessorExists = _globalMilestones.Any(m => m.Id == predecessorId);
        if (!predecessorExists)
        {
            throw new InvalidTemplateDetailsException("The requested predecessor milestone configuration node does not exist within this template context.");
        }

        var edgeWasSevered = successor.RemovePredecessor(predecessorId);
        if (!edgeWasSevered)
        {
            throw new InvalidTemplateDetailsException("An active dependency sequencing constraint link between the specified milestone nodes could not be located.");
        }
    }

    private void EnsureGraphIsAcyclic()
    {
        var evaluationStates = new Dictionary<Guid, bool>();

        foreach (var milestone in _globalMilestones)
        {
            if (!evaluationStates.ContainsKey(milestone.Id))
            {
                if (DetectCycleDfs(milestone.Id, evaluationStates))
                {
                    throw new InvalidOperationException("Dependency rejected: Action introduces an invalid circular reference / DAG loop.");
                }
            }
        }
    }

    private bool DetectCycleDfs(Guid currentId, Dictionary<Guid, bool> states)
    {
        states[currentId] = true;
        var currentMilestone = _globalMilestones.First(m => m.Id == currentId);

        foreach (var dependency in currentMilestone.InboundDependencies)
        {
            if (states.TryGetValue(dependency.PredecessorId, out bool inStack))
            {
                if (inStack)
                {
                    return true;
                }
            }
            else
            {
                if (DetectCycleDfs(dependency.PredecessorId, states))
                {
                    return true;
                }
            }
        }

        states[currentId] = false;
        return false;
    }

    // ==========================================
    // LIFECYCLE WORKFLOWS & WORK INVARIANTS
    // ==========================================

    /// <summary>
    /// Updates the core textual specifications of the template.
    /// </summary>
    public void UpdateDetails(string newTitle, string newDescription)
    {
        if (Status == ProjectTemplateStatus.Approved || Status == ProjectTemplateStatus.Rejected)
        {
            throw new InvalidTemplateStatusException(Status, nameof(UpdateDetails));
        }

        if (string.IsNullOrWhiteSpace(newTitle))
        {
            throw new InvalidTemplateDetailsException("Project template title cannot be empty or whitespace.");
        }

        if (string.IsNullOrWhiteSpace(newDescription))
        {
            throw new InvalidTemplateDetailsException("Project template description cannot be empty or whitespace.");
        }

        Title = newTitle.Trim();
        Description = newDescription.Trim();
    }

    /// <summary>
    /// Submits the drafted or revised project blueprint into the faculty review pool.
    /// Enforces rigorous validation check balances across operational WBS and grading weight configurations.
    /// </summary>
    public void SubmitForReview()
    {
        if (Status != ProjectTemplateStatus.Draft && Status != ProjectTemplateStatus.ChangesRequested)
        {
            throw new InvalidTemplateStatusException(Status, nameof(SubmitForReview));
        }

        // Hard Domain Guard Gate Invariant Checklist
        if (_globalMilestones.Sum(m => m.WbsWeight) != 100)
        {
            throw new InvalidTemplateDetailsException("The cumulative WBS operational weights across all milestones must total exactly 100%.");
        }

        if (_globalMilestones.Sum(m => m.GradingWeight) != 100)
        {
            throw new InvalidTemplateDetailsException("The cumulative academic grading weights across all milestones must total exactly 100%.");
        }

        foreach (var milestone in _globalMilestones)
        {
            if (milestone.GlobalTasks.Sum(t => t.Weight) != 100)
            {
                throw new InvalidTemplateDetailsException($"The cumulative operational task weights inside milestone '{milestone.Title}' must total exactly 100%.");
            }
        }

        Status = ProjectTemplateStatus.PendingReview;

        // Append workflow submission event to safely alert faculty reviewer pools
        AddDomainEvent(new ProjectTemplateSubmittedEvent(Id, ProviderId));
    }

    /// <summary>
    /// Approves the blueprint as-is, closing feedback loops and making it visible to the student platform.
    /// </summary>
    public void Approve()
    {
        if (Status != ProjectTemplateStatus.PendingReview)
        {
            throw new InvalidTemplateStatusException(Status, nameof(Approve));
        }

        Status = ProjectTemplateStatus.Approved;
        ReviewerFeedback = null;

        AddDomainEvent(new ProjectTemplateApprovedEvent(Id, ProviderId));
    }

    /// <summary>
    /// Sends the template back to the provider requesting modifications.
    /// </summary>
    public void RequestChanges(string feedback)
    {
        if (Status != ProjectTemplateStatus.PendingReview)
        {
            throw new InvalidTemplateStatusException(Status, nameof(RequestChanges));
        }

        if (string.IsNullOrWhiteSpace(feedback))
        {
            throw new InvalidTemplateDetailsException("Feedback instructions must be provided to guide the provider's corrections.");
        }

        Status = ProjectTemplateStatus.ChangesRequested;
        ReviewerFeedback = feedback.Trim();

        AddDomainEvent(new ProjectTemplateChangesRequestedEvent(Id, ProviderId, ReviewerFeedback));
    }

    /// <summary>
    /// Allows a reviewer to refine the text parameters directly while pushing the blueprint into confirmation holds.
    /// </summary>
    public void ProposeReviewerChanges(string adjustedTitle, string adjustedDescription)
    {
        if (Status != ProjectTemplateStatus.PendingReview)
        {
            throw new InvalidTemplateStatusException(Status, nameof(ProposeReviewerChanges));
        }

        UpdateDetails(adjustedTitle, adjustedDescription);

        Status = ProjectTemplateStatus.PendingProviderAcceptance;
        ReviewerFeedback = "Reviewer has modified details. Awaiting provider confirmation.";

        AddDomainEvent(new ProjectTemplateReviewerChangesProposedEvent(Id, ProviderId));
    }

    /// <summary>
    /// Executed by the Provider to accept the reviewer's proposed alterations, certifying it live.
    /// </summary>
    public void ProviderAcceptProposedChanges()
    {
        if (Status != ProjectTemplateStatus.PendingProviderAcceptance)
        {
            throw new InvalidTemplateStatusException(Status, nameof(ProviderAcceptProposedChanges));
        }

        Status = ProjectTemplateStatus.Approved;
        ReviewerFeedback = null;

        AddDomainEvent(new ProjectTemplateApprovedEvent(Id, ProviderId));
    }

    /// <summary>
    /// Executed by the Provider to reject the reviewer's proposed alterations, reverting it to a draft layout.
    /// </summary>
    public void ProviderRejectProposedChanges()
    {
        if (Status != ProjectTemplateStatus.PendingProviderAcceptance)
        {
            throw new InvalidTemplateStatusException(Status, nameof(ProviderRejectProposedChanges));
        }

        Status = ProjectTemplateStatus.Draft;
        ReviewerFeedback = "Provider declined reviewer alterations. Reverted back to draft layout.";

        AddDomainEvent(new ProjectTemplateReviewerChangesRejectedEvent(Id, ProviderId));
    }

    /// <summary>
    /// Permanently denies the submission, locking it from subsequent adjustments.
    /// </summary>
    public void RejectPermanently(string reason)
    {
        if (Status != ProjectTemplateStatus.PendingReview)
        {
            throw new InvalidTemplateStatusException(Status, nameof(RejectPermanently));
        }

        if (string.IsNullOrWhiteSpace(reason))
        {
            throw new InvalidTemplateDetailsException("A strict justification reason must be logged for permanent rejection.");
        }

        Status = ProjectTemplateStatus.Rejected;
        ReviewerFeedback = reason.Trim();

        AddDomainEvent(new ProjectTemplateRejectedPermanentlyEvent(Id, ProviderId, ReviewerFeedback));
    }

    // ==========================================
    // SKILLS MAPPING METHODS
    // ==========================================

    /// <summary>
    /// Maps a required tracking skill competency to this template matrix.
    /// </summary>
    public void AddSkill(Guid skillId)
    {
        if (skillId == Guid.Empty)
        {
            throw new InvalidTemplateDetailsException("Skill ID cannot be an empty Guid.");
        }

        if (_projectTemplateSkills.Any(pts => pts.SkillId == skillId))
        {
            return;
        }

        if (_projectTemplateSkills.Count >= 10)
        {
            throw new InvalidTemplateDetailsException("A single project template cannot require more than 10 technical skills.");
        }

        _projectTemplateSkills.Add(new ProjectTemplateSkill(Id, skillId));
    }

    /// <summary>
    /// Removes an existing tracking skill requirements link from this template matrix.
    /// </summary>
    public void RemoveSkill(Guid skillId)
    {
        var skillMapping = _projectTemplateSkills.FirstOrDefault(pts => pts.SkillId == skillId);
        if (skillMapping != null)
        {
            _projectTemplateSkills.Remove(skillMapping);
        }
    }

    // ==========================================
    // PROTOTYPE FACTORY PATTERN METHOD
    // ==========================================

    /// <summary>
    /// Factory Method (Prototype Pattern): Instantiates a brand new, isolated live project workspace 
    /// aggregate root for a student based on this approved template's current point-in-time state snapshot.
    /// </summary>
    public ProjectInstance Instantiate(
        Guid studentId,
        DateTime createdAt,
        LocalMilestoneFactory milestoneFactory,
        Guid? initialRequestedProfessorId = null)
    {
        if (Status != ProjectTemplateStatus.Approved)
        {
            throw new InvalidTemplateStatusException(Status, nameof(Instantiate));
        }

        if (studentId == Guid.Empty)
        {
            throw new InvalidTemplateDetailsException("Student ID cannot be an empty Guid when instantiating a project.");
        }

        if (milestoneFactory == null)
        {
            throw new ArgumentNullException(nameof(milestoneFactory), "The local milestone snapshot factory service is required.");
        }

        var initialStatus = initialRequestedProfessorId.HasValue
            ? ProjectInstanceStatus.AwaitingSupervision
            : ProjectInstanceStatus.Active;

        var skillIdsSnapshot = _projectTemplateSkills.Select(pts => pts.SkillId);

        var projectInstance = new ProjectInstance(
            studentId,
            Id,
            ProviderId,
            Title,
            Description,
            initialStatus,
            createdAt,
            initialRequestedProfessorId,
            skillIdsSnapshot
        );

        var localMilestonesSnapshot = milestoneFactory.CreateLocalMilestonesSnapshot(
            projectInstance.Id,
            this._globalMilestones);

        projectInstance.SeedClonedMilestones(localMilestonesSnapshot);

        return projectInstance;
    }
}